/** Narrow request-only MCP surface for the host-enforced Copilot factory. */
import { writeMessageOut } from '../db/messages-out.js';
import { registerTools } from './server.js';
import type { McpToolDefinition } from './types.js';

function emit(action: string, args: Record<string, unknown>) {
  const requestId = `factory-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  writeMessageOut({ id: requestId, kind: 'system', content: JSON.stringify({ action, requestId, ...args }) });
  return { content: [{ type: 'text' as const, text: `Factory request submitted (${requestId}). A host-verified result will follow.` }] };
}
const str = { type: 'string' as const };
export const factoryTools: McpToolDefinition[] = [
  { tool: { name: 'factory_request_agent_provision', description: 'Request owner approval to provision one constrained child. A requirements-parent must include project_bootstrap; approval atomically creates its shared project channel, parent-first responder, relation, destinations, and derived management actions.', inputSchema: { type: 'object', properties: { template_id: str, display_name: str, requested_actions: { type: 'array', items: { ...str, enum: ['create-child','activate-child','dispatch-child','list-agents','get-status','run-smoke-test','remove-child'] } }, instruction_overlay: str, project_id: str, project_bootstrap: { type: 'object', properties: { project_id: str, platform_id: str }, required: ['project_id','platform_id'] }, repository_id: str, channel_binding: { type: 'object', properties: { channel_type: { ...str, enum: ['discord'] }, platform_id: str, mode: { ...str, enum: ['singleton','project-report','project-alias'] } }, required: ['channel_type','platform_id','mode'] } }, required: ['template_id','display_name'] } }, handler: (a) => emit('provision.request', a) },
  { tool: { name: 'factory_activate_child', description: 'Activate one directly provisioned child without injecting work or creating public traffic.', inputSchema: { type: 'object', properties: { child_agent_group_id: str }, required: ['child_agent_group_id'] } }, handler: (a) => emit('provision.activate', a) },
  { tool: { name: 'factory_dispatch_provisioned_child', description: 'Activate if necessary and dispatch bounded work to one directly provisioned child.', inputSchema: { type: 'object', properties: { child_agent_group_id: str, task: str }, required: ['child_agent_group_id','task'] } }, handler: (a) => emit('provision.dispatch', a) },
  { tool: { name: 'factory_get_status', description: 'Read redacted lifecycle, routing, and model status for an authorized provisioned descendant.', inputSchema: { type: 'object', properties: { child_agent_group_id: str }, required: ['child_agent_group_id'] } }, handler: (a) => emit('provision.get_status', a) },
  { tool: { name: 'factory_request_wake', description: 'Idempotently wake an existing authorized child session without injecting work or public traffic.', inputSchema: { type: 'object', properties: { child_agent_group_id: str }, required: ['child_agent_group_id'] } }, handler: (a) => emit('provision.wake', a) },
  { tool: { name: 'factory_run_smoke_test', description: 'Run the selected child template’s bounded host-defined smoke fixture.', inputSchema: { type: 'object', properties: { child_agent_group_id: str }, required: ['child_agent_group_id'] } }, handler: (a) => emit('provision.smoke', a) },
  { tool: { name: 'factory_get_smoke_test', description: 'Read the latest redacted smoke-test result for an authorized child.', inputSchema: { type: 'object', properties: { child_agent_group_id: str }, required: ['child_agent_group_id'] } }, handler: (a) => emit('provision.get_smoke', a) },
  { tool: { name: 'factory_list_provisioned_children', description: 'List only directly provisioned children for which the caller has a derived list grant.', inputSchema: { type: 'object', properties: {} } }, handler: () => emit('provision.list_children', {}) },
  { tool: { name: 'factory_remove_provisioned_child', description: 'Revoke one directly provisioned child subtree when the owner-approved removal grant exists.', inputSchema: { type: 'object', properties: { child_agent_group_id: str }, required: ['child_agent_group_id'] } }, handler: (a) => emit('provision.remove', a) },
  { tool: { name: 'factory_list_agents', description: 'List Copilot factory-managed agents. Read-only.', inputSchema: { type: 'object', properties: {} } }, handler: () => emit('factory.list_agents', {}) },
  { tool: { name: 'factory_get_agent', description: 'Read one factory-managed agent.', inputSchema: { type: 'object', properties: { agent_group_id: str }, required: ['agent_group_id'] } }, handler: (a) => emit('factory.get_agent', { agent_group_id: a.agent_group_id }) },
  { tool: { name: 'factory_update_instructions', description: 'Update only a managed agent instruction overlay using its current revision.', inputSchema: { type: 'object', properties: { agent_group_id: str, expected_revision: str, instructions_patch: str }, required: ['agent_group_id','expected_revision','instructions_patch'] } }, handler: (a) => emit('factory.update_instructions', a) },
  { tool: { name: 'factory_request_capability_change', description: 'Request owner approval for a capability; this never applies it.', inputSchema: { type: 'object', properties: { agent_group_id: str, category: str, reason: str, target: str }, required: ['agent_group_id','category','reason','target'] } }, handler: (a) => emit('factory.request_capability_change', a) },
  { tool: { name: 'factory_wire_agent_channel', description: 'Wire an explicitly granted managed descendant to one Discord server channel. The host fixes the routing policy.', inputSchema: { type: 'object', properties: { agent_group_id: str, channel_type: { ...str, enum: ['discord'] }, platform_id: str }, required: ['agent_group_id','channel_type','platform_id'] } }, handler: (a) => emit('factory.wire_agent_channel', a) },
  { tool: { name: 'factory_list_channel_wirings', description: 'List channel wirings for managed descendants that the host permits you to inspect.', inputSchema: { type: 'object', properties: { agent_group_id: str } } }, handler: (a) => emit('factory.list_channel_wirings', a) },
  { tool: { name: 'factory_unwire_agent_channel', description: 'Remove only one exact host-owned managed-agent Discord wiring.', inputSchema: { type: 'object', properties: { agent_group_id: str, channel_type: { ...str, enum: ['discord'] }, platform_id: str }, required: ['agent_group_id','channel_type','platform_id'] } }, handler: (a) => emit('factory.unwire_agent_channel', a) },
  { tool: { name: 'factory_dispatch_child', description: 'Dispatch bounded work to an explicitly authorized existing child.', inputSchema: { type: 'object', properties: { child_agent_group_id: str, task: str }, required: ['child_agent_group_id','task'] } }, handler: (a) => emit('factory.dispatch_child', a) },
  { tool: { name: 'project_dispatch_child', description: 'Dispatch one bounded task to a live project descendant. This does not send a public channel message.', inputSchema: { type: 'object', properties: { project_id: str, agent_group_id: str, task: str }, required: ['project_id','agent_group_id','task'] } }, handler: (a) => emit('project.dispatch_child', a) },
  { tool: { name: 'project_wire_descendant', description: 'Idempotently project a descendant’s already host-created destinations into its sessions.', inputSchema: { type: 'object', properties: { project_id: str, agent_group_id: str }, required: ['project_id','agent_group_id'] } }, handler: (a) => emit('project.wire_descendant', a) },
  { tool: { name: 'project_remove_descendant', description: 'Remove only a live project descendant and its host-created routes.', inputSchema: { type: 'object', properties: { project_id: str, agent_group_id: str }, required: ['project_id','agent_group_id'] } }, handler: (a) => emit('project.remove_descendant', a) },
  { tool: { name: 'project_list_agents', description: 'List live descendants when the caller has a project status capability.', inputSchema: { type: 'object', properties: { project_id: str }, required: ['project_id'] } }, handler: (a) => emit('project.list_agents', a) },
  { tool: { name: 'project_get_status', description: 'Read one descendant lifecycle status when the caller has a project status capability.', inputSchema: { type: 'object', properties: { project_id: str, agent_group_id: str }, required: ['project_id','agent_group_id'] } }, handler: (a) => emit('project.get_status', a) },
];
registerTools(factoryTools);
